# Generated by Django 5.2.15 on 2026-08-22 21:50

from django.db import migrations, models


def seed_initial_settings(apps, schema_editor):
    SystemSetting = apps.get_model('core', 'SystemSetting')
    defaults = [
        # Identité
        ('SCHOOL_NAME', 'Centre Tonaroz', 'Nom du centre', 'SCHOOL'),
        ('SCHOOL_SUBTITLE', 'Soutien Scolaire & Langues', 'Sous-titre / Description', 'SCHOOL'),
        ('SCHOOL_ADDRESS', 'Rue Marrakech, Im 16, Ap N 3, 2ème Étage, Khouribga', 'Adresse', 'SCHOOL'),
        ('SCHOOL_PHONE', '0707477911 / 0661569522', 'Téléphones', 'SCHOOL'),
        ('SCHOOL_EMAIL', 'contact@centre-tonaroz.com', 'Email de contact', 'SCHOOL'),
        ('SCHOOL_LOGO_PATH', 'images/tonaroz_logo.svg', 'Chemin du logo', 'SCHOOL'),
        
        # Finances & Reçus
        ('CURRENCY_SYMBOL', 'DH', 'Symbole monétaire', 'FINANCE'),
        ('ENABLE_PRORATION', 'True', 'Activer la proratisation mensuelle', 'FINANCE'),
        ('LATE_PAYMENT_GRACE_DAYS', '5', 'Jours de grâce retard paiement', 'FINANCE'),
        ('RECEIPT_FOOTER_THANK_YOU', 'Merci pour votre confiance ! - شكراً لثقتكم', 'Pied de reçu (Message de remerciement)', 'FINANCE'),
        
        # WhatsApp
        ('WHATSAPP_API_KEY', '', 'Clé API WhatsApp Service', 'WHATSAPP'),
        ('WHATSAPP_SERVICE_PORT', '3000', 'Port du service WhatsApp', 'WHATSAPP'),
        ('WHATSAPP_SESSION_NOTIFICATIONS_ENABLED', 'True', 'Alertes WhatsApp modif sessions', 'WHATSAPP'),
        ('WHATSAPP_AUTO_ABSENCE_NOTIFICATIONS', 'True', 'Alertes WhatsApp absences', 'WHATSAPP'),
        
        # Kiosque & Portails
        ('KIOSK_TIMEOUT', '45', 'Délai inactivité Kiosque (sec)', 'KIOSK'),
        ('KIOSK_SEARCH_ENABLED', 'True', 'Recherche élève Kiosque autorisée', 'KIOSK'),
        
        # Planning & Salles
        ('CONFLICT_CACHE_TTL', '120', 'Durée cache conflits (sec)', 'SCHEDULING'),
        ('RESCHEDULING_SEARCH_HORIZON', '21', 'Horizon recherche reprogrammation (jours)', 'SCHEDULING'),
        ('CAPACITY_WARNING_MARGIN', '2', 'Marge alerte capacité salle', 'SCHEDULING'),
        ('CAPACITY_NEAR_LIMIT_RATIO', '0.9', 'Seuil ratio occupation salle', 'SCHEDULING'),
        
        # Paie
        ('DEFAULT_TEACHER_PAYMENT_METHOD', 'SESSION', 'Mode calcul paie prof par défaut', 'PAYROLL'),
    ]
    for key, val, label, group in defaults:
        SystemSetting.objects.get_or_create(key=key, defaults={'value': val, 'label': label, 'group': group})


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0045_coursegroup_requires_accessibility_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        db_index=True, max_length=100, unique=True, verbose_name="Clé"
                    ),
                ),
                ("value", models.TextField(blank=True, verbose_name="Valeur")),
                (
                    "label",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Libellé"
                    ),
                ),
                (
                    "group",
                    models.CharField(
                        default="GENERAL", max_length=50, verbose_name="Groupe"
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètre système",
                "verbose_name_plural": "Paramètres système",
            },
        ),
        migrations.RunPython(seed_initial_settings, reverse_code=migrations.RunPython.noop),
    ]

