# Generated by Django 5.2.15 on 2026-08-27 13:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0046_systemsetting"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sessionchangehistory",
            name="handled_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Traité le"),
        ),
        migrations.AddField(
            model_name="sessionchangehistory",
            name="is_handled",
            field=models.BooleanField(default=False, verbose_name="Traité / Notifié"),
        ),
        migrations.AddIndex(
            model_name="sessionchangehistory",
            index=models.Index(
                fields=["is_handled"], name="core_sessio_is_hand_da0989_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sessionchangehistory",
            index=models.Index(
                fields=["session", "is_handled"], name="core_sessio_session_6cf128_idx"
            ),
        ),
    ]
