# Generated by Django 5.2.15 on 2026-08-27 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0047_sessionchangehistory_handled_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="enrollment",
            name="whatsapp_invite_sent",
            field=models.BooleanField(
                default=False, verbose_name="Lien WhatsApp envoyé"
            ),
        ),
        migrations.AlterField(
            model_name="whatsappsendlog",
            name="message_type",
            field=models.CharField(
                choices=[
                    ("payment_reminder", "Rappel de paiement"),
                    ("payment_confirmation", "Confirmation de paiement"),
                    ("absence_notification", "Notification d'absence"),
                    ("session_reminder", "Rappel de séance"),
                    ("bulk_announcement", "Annonce groupée"),
                    ("group_invite", "Lien groupe WhatsApp"),
                    ("other", "Autre"),
                ],
                default="other",
                max_length=30,
                verbose_name="Type de message",
            ),
        ),
    ]
