# Generated by Django 5.2.15 on 2026-09-05 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_enrollment_whatsapp_invite_sent_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='coursegroupschedule',
            index=models.Index(fields=['room', 'day'], name='core_course_room_id_814e79_idx'),
        ),
        migrations.AddIndex(
            model_name='coursegroupschedule',
            index=models.Index(fields=['course_group', 'day'], name='core_course_course__78bb2f_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['is_active'], name='core_enroll_is_acti_fcc59a_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['student', 'is_active'], name='core_enroll_student_7edad6_idx'),
        ),
        migrations.AddIndex(
            model_name='enrollment',
            index=models.Index(fields=['course_group', 'is_active'], name='core_enroll_course__bec996_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status'], name='core_paymen_status_8390cc_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['month_covered', 'status'], name='core_paymen_month_c_b0c7de_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['payment_date', 'status'], name='core_paymen_payment_be6030_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['student', 'month_covered'], name='core_paymen_student_1ea0fa_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['is_active'], name='core_studen_is_acti_d09166_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['is_active', 'name'], name='core_studen_is_acti_ed5b60_idx'),
        ),
    ]
