# Generated by Django 5.2.15 on 2026-09-20 17:18

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


def populate_group_levels(apps, schema_editor):
    CourseGroup = apps.get_model('core', 'CourseGroup')
    for group in CourseGroup.objects.all():
        if group.level_id:
            group.levels.add(group.level_id)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_performance_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroup',
            name='levels',
            field=models.ManyToManyField(blank=True, related_name='course_groups', to='core.level', verbose_name='Niveaux'),
        ),
        migrations.AddField(
            model_name='level',
            name='next_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='previous_levels', to='core.level', verbose_name='Niveau suivant'),
        ),
        migrations.AddField(
            model_name='level',
            name='order',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordre de progression'),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='legacy_course_groups', to='core.level', verbose_name='Niveau principal (legacy)'),
        ),
        migrations.CreateModel(
            name='StudentLevelHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date de changement')),
                ('reason', models.CharField(default='Progression automatique', max_length=255, verbose_name='Motif')),
                ('notes', models.TextField(blank=True, verbose_name='Notes')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Effectué par')),
                ('from_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.level', verbose_name='Ancien niveau')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='level_history', to='core.student', verbose_name='Élève')),
                ('to_level', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='core.level', verbose_name='Nouveau niveau')),
            ],
            options={
                'verbose_name': 'Historique de niveau',
                'verbose_name_plural': 'Historiques de niveaux',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.RunPython(populate_group_levels, migrations.RunPython.noop),
    ]
