# Generated by Django 5.2.15 on 2026-09-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_coursegroup_levels_level_next_level_level_order_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='level',
            options={'ordering': ['category', 'order', 'name'], 'verbose_name': 'Niveau', 'verbose_name_plural': 'Niveaux'},
        ),
        migrations.AddField(
            model_name='level',
            name='level_type',
            field=models.CharField(choices=[('ACADEMIC', 'Académique'), ('NON_ACADEMIC', 'Non académique')], default='ACADEMIC', max_length=20, verbose_name='Type de niveau'),
        ),
        migrations.AddField(
            model_name='levelcategory',
            name='is_academic',
            field=models.BooleanField(default=True, verbose_name='Catégorie académique'),
        ),
    ]
