"""
Django settings for school_erp project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
from django.templatetags.static import static
from django.urls import reverse_lazy
import os
import secrets
import dj_database_url

# Load environment variables from .env file if present
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass

from core.paths import (
    get_base_dir,
    get_data_dir,
    get_database_path,
    get_media_dir,
    get_logs_dir,
    ensure_data_directories,
)
from core.version import VERSION

# Ensure writable customer data directories exist
ensure_data_directories()

# Early license check to prevent unauthorized use when Django imports settings
from core.license import validate_or_exit
validate_or_exit()

# Application root directory (immutable code and templates)
BASE_DIR = get_base_dir()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# Supports both DJANGO_SECRET_KEY and SECRET_KEY
SECRET_KEY = (
    os.environ.get('DJANGO_SECRET_KEY')
    or os.environ.get('SECRET_KEY')
    or 'm9s0r9ex$&lg(4pk0t8lbh7nm#^u03j6q)v-y4z(!y4i-+hg*$nMvB5sLBZjeuZITYbn04kRPOllNzOh_HeI9UWs9qJfP5WkR33HQAAv3ltPLeZOV4QXA'
)

# SECURITY WARNING: don't run with debug turned on in production!
# Supports both DJANGO_DEBUG and DEBUG
_raw_debug = os.environ.get('DJANGO_DEBUG') or os.environ.get('DEBUG')
if _raw_debug is not None:
    DEBUG = str(_raw_debug).strip().lower() not in ('false', '0', 'no', 'off')
else:
    DEBUG = True

# Comma-separated list of allowed hosts, e.g. DJANGO_ALLOWED_HOSTS=mysite.com,www.mysite.com
_raw_hosts = os.environ.get('DJANGO_ALLOWED_HOSTS') or os.environ.get('ALLOWED_HOSTS', '*')
ALLOWED_HOSTS = [h.strip() for h in _raw_hosts.split(',') if h.strip()]

# Trusted origins for CSRF (required when served behind a proxy / on HTTPS).
_raw_csrf = os.environ.get('DJANGO_CSRF_TRUSTED_ORIGINS') or os.environ.get('CSRF_TRUSTED_ORIGINS', '')
CSRF_TRUSTED_ORIGINS = [o.strip() for o in _raw_csrf.split(',') if o.strip()]

# ── Railway / Cloud Automatic Host & CSRF Configuration ─────────────────────
_railway_domain = os.environ.get('RAILWAY_PUBLIC_DOMAIN') or os.environ.get('RAILWAY_STATIC_URL')
if _railway_domain:
    _clean_domain = _railway_domain.replace("https://", "").replace("http://", "").rstrip("/")
    if _clean_domain not in ALLOWED_HOSTS and "*" not in ALLOWED_HOSTS:
        ALLOWED_HOSTS.append(_clean_domain)
    _railway_origin = f"https://{_clean_domain}"
    if _railway_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(_railway_origin)



# Application definition

INSTALLED_APPS = [
    "unfold",
    "unfold.contrib.import_export",
    
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',
    "django.contrib.sites",

    'import_export',
    'django_filters',
    'django_extensions',
    "django_htmx",

    'core',
]

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedStaticFilesStorage",
    },
}

# Ensure missing static assets never crash template rendering
WHITENOISE_MANIFEST_STRICT = False




# Settings for school center (configurable)
SCHOOL_NAME = "Centre My2i"
SCHOOL_ADDRESS = "Rue Marrakech, Im 16, Ap N 3, 2ème Étage, Khouribga"
SCHOOL_PHONE = "0707477911 / 0661569522"
SCHOOL_EMAIL = "contact@centre-tonaroz.com"
SCHOOL_LOGO_PATH = 'images/tonaroz_logo.svg'
KIOSK_TIMEOUT = 45



UNFOLD = {
    "SITE_TITLE": f"Admin {SCHOOL_NAME}",
    "SITE_HEADER": SCHOOL_NAME,
    "SITE_SYMBOL": "local_library",           # Material symbol name
    "SHOW_HISTORY": True,
    "DARK_MODE": True,

    # ── Inject our custom CSS after Unfold's CSS ──
    "STYLES": [
        lambda request: static("admin/css/school_admin.css"),
    ],

    # ── Custom blue colour palette matching Afnane center ──
    "COLORS": {
        "font": {
            "subtle-light":   "107 114 128",   # gray-500
            "subtle-dark":    "156 163 175",   # gray-400
            "default-light":  "17 24 39",      # gray-900
            "default-dark":   "243 244 246",   # gray-100
            "important-light":"0 0 0",
            "important-dark": "255 255 255",
        },
        "primary": {
            "50":  "239 246 255",   # blue-50
            "100": "219 234 254",   # blue-100
            "200": "191 219 254",   # blue-200
            "300": "147 197 253",   # blue-300
            "400": "96 165 250",    # blue-400
            "500": "59 130 246",    # blue-500
            "600": "37 99 235",     # blue-600 ← main
            "700": "29 78 216",     # blue-700
            "800": "30 64 175",     # blue-800
            "900": "30 58 138",     # blue-900
            "950": "23 37 84",      # blue-950
        },
    },

    # ── Sidebar navigation groups with icons ──
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": False,
        "navigation": [
            {
                "title": "Tableau de bord",
                "separator": False,
                "items": [
                    {
                        "title": "Accueil",
                        "icon": "home",
                        "link": reverse_lazy("admin:index"),
                    },
                ],
            },
            {
                "title": "Élèves & Inscriptions",
                "separator": True,
                "items": [
                    {
                        "title": "Élèves",
                        "icon": "school",
                        "link": reverse_lazy("admin:core_student_changelist"),
                    },
                    {
                        "title": "Paiements",
                        "icon": "payments",
                        "link": reverse_lazy("admin:core_payment_changelist"),
                    },
                    {
                        "title": "Présences",
                        "icon": "fact_check",
                        "link": reverse_lazy("admin:core_attendance_changelist"),
                    },
                ],
            },
            {
                "title": "Organisation",
                "separator": True,
                "items": [
                    {
                        "title": "Groupes de cours",
                        "icon": "groups",
                        "link": reverse_lazy("admin:core_coursegroup_changelist"),
                    },
                    {
                        "title": "Professeurs",
                        "icon": "person_book",
                        "link": reverse_lazy("admin:core_teacher_changelist"),
                    },
                    {
                        "title": "Salles",
                        "icon": "meeting_room",
                        "link": reverse_lazy("admin:core_room_changelist"),
                    },
                    {
                        "title": "Niveaux",
                        "icon": "school",
                        "link": reverse_lazy("admin:core_level_changelist"),
                    },
                    {
                        "title": "Catégories de niveau",
                        "icon": "category",
                        "link": reverse_lazy("admin:core_levelcategory_changelist"),
                    },
                    {
                        "title": "Paie Professeurs",
                        "icon": "money",
                        "link": reverse_lazy("admin:core_teacherpayment_changelist"),
                    },
                    {
                        "title": "Messages WhatsApp",
                        "icon": "message",
                        "link": reverse_lazy("admin:message_templates"),
                    },
                    {
                        "title": "Annonce",
                        "icon": "announcement",
                        "link": reverse_lazy("admin:core_announcement_changelist"),
                    }
                ],
            },
            {
                "title": "Analytiques & Rapports",
                "separator": True,
                "items": [
                    {
                        "title": "Cockpit Directeur",
                        "icon": "dashboard",
                        "link": reverse_lazy("admin:analytics_dashboard"),
                    },
                    {
                        "title": "Analyse de Revenus",
                        "icon": "payments",
                        "link": reverse_lazy("admin:analytics_revenue"),
                    },
                    {
                        "title": "Suivi des Absences",
                        "icon": "fact_check",
                        "link": reverse_lazy("admin:analytics_attendance"),
                    },
                    {
                        "title": "Rétention & Départs",
                        "icon": "trending_down",
                        "link": reverse_lazy("admin:analytics_students"),
                    },
                    {
                        "title": "Occupation des Salles",
                        "icon": "meeting_room",
                        "link": reverse_lazy("admin:analytics_rooms"),
                    },
                    {
                        "title": "Paie Enseignants",
                        "icon": "calculate",
                        "link": reverse_lazy("admin:analytics_teachers"),
                    },
                    {
                        "title": "Santé Opérationnelle",
                        "icon": "analytics",
                        "link": reverse_lazy("admin:analytics_operational"),
                    }
                ],
            }
        ],
    },
}


DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # WhiteNoise must be placed directly after SecurityMiddleware so it can
    # serve compressed static files efficiently before any other middleware.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    "django_htmx.middleware.HtmxMiddleware",
    "django.contrib.sites.middleware.CurrentSiteMiddleware",
    'core.middleware.AdminOnlyMiddleware',
]

ROOT_URLCONF = 'school_erp.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': False,
        'OPTIONS': {
            'loaders': [
                'core.loaders.DecryptedFilesystemLoader',
                'django.template.loaders.app_directories.Loader',
            ],
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.conflicts_count',
                'core.context_processors.whatsapp_status',
                'core.context_processors.school_info',
            ],
        },
    },
]

WSGI_APPLICATION = 'school_erp.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
#
# ── Database selection ───────────────────────────────────────────────────────
# Production (cloud):  set DATABASE_URL to a PostgreSQL connection string, e.g.
#   DATABASE_URL=postgres://user:password@host:5432/dbname
#   dj-database-url parses it and configures Django automatically.
#
# Local development:   leave DATABASE_URL unset → SQLite with WAL mode.
# ─────────────────────────────────────────────────────────────────────────────

_DATABASE_URL = (
    os.environ.get("DATABASE_URL")
    or os.environ.get("POSTGRES_URL")
    or os.environ.get("DATABASE_PUBLIC_URL")
    or os.environ.get("PGDATABASE_URL")
    or ""
).strip()

_parsed_db = None
if _DATABASE_URL and "://" in _DATABASE_URL and not _DATABASE_URL.startswith("://"):
    try:
        _parsed_db = dj_database_url.parse(
            _DATABASE_URL,
            conn_max_age=600,       # keep connections alive for 10 min
            conn_health_checks=True,
        )
    except Exception:
        _parsed_db = None

if _parsed_db:
    # ── PostgreSQL / External Database (production) ───────────────────────────
    DATABASES = {
        "default": _parsed_db
    }
else:
    # ── SQLite + WAL mode (local development) ───────────────────────────────
    #
    # WAL (Write-Ahead Logging) allows concurrent readers while a writer is
    # active, which significantly reduces "database is locked" errors in LAN
    # multi-user scenarios.
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': get_database_path(),
            "OPTIONS": {
                # Python-level connection timeout (seconds).
                "timeout": 30,
                # PRAGMAs run after every new connection:
                #   journal_mode=WAL    — enables WAL mode.
                #   synchronous=NORMAL  — sufficient durability under WAL.
                #   busy_timeout=30000  — wait up to 30 s before raising error.
                "init_command": (
                    "PRAGMA journal_mode=WAL;"
                    "PRAGMA synchronous=NORMAL;"
                    "PRAGMA busy_timeout=30000;"
                ),
            },
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = "Africa/Casablanca"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (Customer uploads in writable data directory)
MEDIA_URL = '/media/'
MEDIA_ROOT = get_media_dir()

LOGIN_REDIRECT_URL = 'core:cockpit'
LOGOUT_REDIRECT_URL = '/admin/login/'


# WhatsApp integration settings
WHATSAPP_API_KEY = os.environ.get('WA_API_KEY', '')
WHATSAPP_SESSION_NOTIFICATIONS_ENABLED = True  # Set to True to enable WhatsApp session notifications
WHATSAPP_SERVICE_PORT = os.environ.get("WA_PORT", 3000)
# Host where the WhatsApp Node service is reachable from Django.
# On single-container platforms (Railway, Render) both processes share the
# same host, so localhost is correct.  On multi-container setups, set
# WA_SERVICE_HOST to the internal service name or IP.
WHATSAPP_SERVICE_HOST = os.environ.get("WA_SERVICE_HOST", "localhost")

SESSION_EXPIRE_AT_BROWSER_CLOSE = True

SITE_ID = 1

# ── Production HTTPS / security hardening ────────────────────────────────────
# These are safe no-ops in development (DEBUG=True).  When you deploy with
# DEBUG=False and HTTPS, they enforce secure cookies and tell browsers to only
# ever connect over HTTPS (HSTS).  Leave them here; your hosting env controls
# whether they are active via the DJANGO_DEBUG env variable.
if not DEBUG:
    SECURE_SSL_REDIRECT = True          # redirect all HTTP → HTTPS
    SECURE_HSTS_SECONDS = 31536000      # 1 year HSTS header
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SESSION_COOKIE_SECURE = True        # session cookie over HTTPS only
    CSRF_COOKIE_SECURE = True           # CSRF cookie over HTTPS only
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Production Logging Configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'standard': {
            'format': '[%(asctime)s] [%(levelname)s] [%(name)s]: %(message)s',
            'datefmt': '%Y-%m-%d %H:%M:%S',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'standard',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': str(get_logs_dir() / 'django.log'),
            'maxBytes': 5 * 1024 * 1024,  # 5 MB
            'backupCount': 3,
            'formatter': 'standard',
            'encoding': 'utf-8',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
        'core': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

