#!/usr/bin/env python3
"""
build_patch.py  –  Partial Client Patch Builder
================================================
Produces an encrypted / obfuscated patch for:
  1. core/views.py              → core/views.pyc  +  core/views.py (shim)
  2. whatsapp_service/server.js → whatsapp_service/server.js (obfuscated)
  3. templates/core/whatsapp_dashboard.html → encrypted / packaged template

Template Encryption Modes:
--------------------------
  --plain-template       (Default & Safest for single template update)
                         Leaves whatsapp_dashboard.html in plain HTML.
                         The client's DecryptedFilesystemLoader automatically
                         detects that it's unencrypted and loads it directly,
                         without breaking any other encrypted templates!

  --fernet-key <KEY>     If you saved the client's original Fernet key from
                         their build, pass it here to encrypt whatsapp_dashboard.html
                         with their exact key.

  --new-key-all-templates Generates a new Fernet key, encrypts ALL templates
                         and updates core/loaders.pyc. Use this if you want
                         every template re-encrypted under the new key.

Usage:
------
  python tools/build_patch.py
  python tools/build_patch.py --client ClientName
  python tools/build_patch.py --fernet-key <KEY>
  python tools/build_patch.py --new-key-all-templates
"""

from __future__ import annotations

import argparse
import os
import py_compile
import shutil
import subprocess
import sys
import tempfile
import zipfile
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent

ENC_MARKER = b"FENC\x00"

LOADER_TEMPLATE = '''\
# Auto-generated by build_patch.py. Do NOT commit to VCS.
from django.template.loaders.filesystem import Loader as FilesystemLoader
from django.template import TemplateDoesNotExist
from cryptography.fernet import Fernet as _Fernet

_FERNET_KEY = {key_repr}
_ENC_MARKER = {marker_repr}
_fernet     = _Fernet(_FERNET_KEY)


class DecryptedFilesystemLoader(FilesystemLoader):
    """Template loader that transparently decrypts Fernet-encrypted templates."""

    def get_contents(self, origin):
        try:
            with open(origin.name, "rb") as fp:
                data = fp.read()
            if data.startswith(_ENC_MARKER):
                decrypted = _fernet.decrypt(data[len(_ENC_MARKER):])
                return decrypted.decode(self.engine.file_charset)
            return data.decode(self.engine.file_charset)
        except FileNotFoundError:
            raise TemplateDoesNotExist(origin)
'''


def _banner(msg: str) -> None:
    print(f"\n{'=' * 60}\n  {msg}\n{'=' * 60}", flush=True)


def _ok(msg: str) -> None:
    print(f"  [OK]  {msg}", flush=True)


def _info(msg: str) -> None:
    print(f"        {msg}", flush=True)


def _fail(msg: str) -> None:
    print(f"  [ERR] {msg}", file=sys.stderr, flush=True)


# ============================================================
# Step 1 – Compile views.py to .pyc + shim
# ============================================================

def build_views(patch_dir: Path) -> None:
    _banner("STEP 1 - Compile core/views.py -> views.pyc")

    src = PROJECT_ROOT / "core" / "views.py"
    if not src.exists():
        raise FileNotFoundError(f"views.py not found: {src}")

    out_dir = patch_dir / "core"
    out_dir.mkdir(parents=True, exist_ok=True)

    dest_pyc = out_dir / "views.pyc"
    dest_py  = out_dir / "views.py"

    py_compile.compile(str(src), cfile=str(dest_pyc), doraise=True)
    _ok(f"Compiled  core/views.py -> core/views.pyc ({dest_pyc.stat().st_size // 1024} KB)")

    shim = (
        "import os, runpy\n"
        "_g = runpy.run_path(os.path.join(os.path.dirname(__file__), 'views.pyc'), run_name=__name__)\n"
        "globals().update(_g)\n"
    )
    dest_py.write_text(shim, encoding="utf-8")
    _ok("Written   core/views.py (loader shim)")


# ============================================================
# Step 2 – Obfuscate server.js
# ============================================================

def build_server_js(patch_dir: Path) -> None:
    _banner("STEP 2 - Obfuscate whatsapp_service/server.js")

    src = PROJECT_ROOT / "whatsapp_service" / "server.js"
    if not src.exists():
        raise FileNotFoundError(f"server.js not found: {src}")

    out_dir = patch_dir / "whatsapp_service"
    out_dir.mkdir(parents=True, exist_ok=True)
    dest = out_dir / "server.js"

    obfuscated = False

    with tempfile.TemporaryDirectory() as tmp:
        tmp_out = Path(tmp) / "server.js"
        
        # On Windows, invoke npx via cmd.exe to bypass PowerShell execution policies
        if sys.platform == "win32":
            cmd = [
                "cmd.exe", "/c", "npx.cmd", "--yes", "javascript-obfuscator", str(src),
                "--output", str(tmp_out),
                "--compact", "true",
                "--identifier-names-generator", "hexadecimal",
                "--string-array", "true",
                "--string-array-encoding", "rc4",
                "--self-defending", "true",
                "--disable-console-output", "false",
            ]
        else:
            npx = shutil.which("npx") or "npx"
            cmd = [
                npx, "--yes", "javascript-obfuscator", str(src),
                "--output", str(tmp_out),
                "--compact", "true",
                "--identifier-names-generator", "hexadecimal",
                "--string-array", "true",
                "--string-array-encoding", "rc4",
                "--self-defending", "true",
                "--disable-console-output", "false",
            ]

        try:
            _info("Running javascript-obfuscator via npx...")
            r = subprocess.run(cmd, capture_output=True, text=True, timeout=60, cwd=str(PROJECT_ROOT))
            if r.returncode == 0 and tmp_out.exists() and tmp_out.stat().st_size > 256:
                shutil.copy2(tmp_out, dest)
                obfuscated = True
                _ok(f"Obfuscated server.js ({dest.stat().st_size // 1024} KB)")
            else:
                err = (r.stderr or r.stdout or "").strip()
                if err:
                    _info(f"javascript-obfuscator output: {err[:300]}")
        except Exception as exc:
            _info(f"javascript-obfuscator execution error: {exc}")

    if not obfuscated:
        shutil.copy2(src, dest)
        _info("WARNING: javascript-obfuscator failed; copied original server.js")


# ============================================================
# Step 3 – Templates
# ============================================================

def build_templates(patch_dir: Path, mode: str, fernet_key: str | None = None) -> None:
    _banner("STEP 3 - Package / Encrypt Template")

    out_tpl_dir = patch_dir / "templates" / "core"
    out_tpl_dir.mkdir(parents=True, exist_ok=True)
    tpl_src = PROJECT_ROOT / "templates" / "core" / "whatsapp_dashboard.html"

    if not tpl_src.exists():
        raise FileNotFoundError(f"Template not found: {tpl_src}")

    if mode == "fernet-key" and fernet_key:
        from cryptography.fernet import Fernet
        f = Fernet(fernet_key.encode("utf-8") if isinstance(fernet_key, str) else fernet_key)
        raw = tpl_src.read_bytes()
        encrypted = ENC_MARKER + f.encrypt(raw)
        (out_tpl_dir / "whatsapp_dashboard.html").write_bytes(encrypted)
        _ok(f"Encrypted whatsapp_dashboard.html using provided Fernet key ({len(encrypted) // 1024} KB)")

    elif mode == "new-key-all":
        from cryptography.fernet import Fernet
        key = Fernet.generate_key()
        f = Fernet(key)

        # Encrypt all templates in templates/
        tpl_root = PROJECT_ROOT / "templates"
        dest_tpl_root = patch_dir / "templates"
        count = 0
        for root, _, files in os.walk(tpl_root):
            for fname in files:
                src_p = Path(root) / fname
                rel_p = src_p.relative_to(tpl_root)
                dest_p = dest_tpl_root / rel_p
                dest_p.parent.mkdir(parents=True, exist_ok=True)

                raw = src_p.read_bytes()
                if fname.endswith((".html", ".txt", ".xml")):
                    enc = ENC_MARKER + f.encrypt(raw)
                    dest_p.write_bytes(enc)
                    count += 1
                else:
                    shutil.copy2(src_p, dest_p)

        _ok(f"Re-encrypted all {count} templates with fresh Fernet key.")

        # Recompile loaders.py with the new key
        out_core_dir = patch_dir / "core"
        out_core_dir.mkdir(parents=True, exist_ok=True)
        loader_src = LOADER_TEMPLATE.format(
            key_repr=repr(key),
            marker_repr=repr(ENC_MARKER),
        )
        loader_py = out_core_dir / "loaders.py"
        loader_pyc = out_core_dir / "loaders.pyc"
        loader_py.write_text(loader_src, encoding="utf-8")
        py_compile.compile(str(loader_py), cfile=str(loader_pyc), doraise=True)
        shim = (
            "import os, runpy\n"
            "_g = runpy.run_path(os.path.join(os.path.dirname(__file__), 'loaders.pyc'), run_name=__name__)\n"
            "globals().update(_g)\n"
        )
        loader_py.write_text(shim, encoding="utf-8")
        _ok("Compiled core/loaders.pyc + shim with new Fernet key")

    else:
        # Default: Plain template. DecryptedFilesystemLoader handles unencrypted files transparently!
        dest_file = out_tpl_dir / "whatsapp_dashboard.html"
        shutil.copy2(tpl_src, dest_file)
        _ok("Packaged  templates/core/whatsapp_dashboard.html (compatible with client DecryptedFilesystemLoader)")
        _info("Note: DecryptedFilesystemLoader loads unencrypted templates directly without key dependency.")


# ============================================================
# Step 4 – Package into ZIP
# ============================================================

def create_zip(patch_dir: Path, zip_path: Path) -> None:
    _banner("STEP 4 - Create Patch ZIP Package")

    zip_path.parent.mkdir(parents=True, exist_ok=True)
    if zip_path.exists():
        zip_path.unlink()

    with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zf:
        for root, dirs, files in os.walk(patch_dir):
            dirs[:] = [d for d in dirs if d != "__pycache__"]
            for fname in files:
                abs_p = Path(root) / fname
                rel_p = abs_p.relative_to(patch_dir)
                zf.write(abs_p, rel_p)

    _ok(f"ZIP created: {zip_path} ({zip_path.stat().st_size / 1024:.1f} KB)")


# ============================================================
# Main
# ============================================================

def parse_args() -> argparse.Namespace:
    p = argparse.ArgumentParser(description="School ERP - Partial Patch Builder")
    p.add_argument("--client", default="client_update", help="Client name or slug for the ZIP filename")
    p.add_argument("--fernet-key", default=None, help="The client's original Fernet key (if known)")
    p.add_argument("--new-key-all-templates", action="store_true", help="Re-encrypt ALL templates and include updated loaders.pyc")
    p.add_argument("--output", default=None, help="Custom output ZIP path")
    return p.parse_args()


def main() -> int:
    args = parse_args()

    zip_path = (
        Path(args.output).resolve()
        if args.output
        else PROJECT_ROOT / "build" / "patch" / f"SchoolERP-Update-{args.client}.zip"
    )

    mode = "plain"
    if args.fernet_key:
        mode = "fernet-key"
    elif args.new_key_all_templates:
        mode = "new-key-all"

    with tempfile.TemporaryDirectory(prefix="erp_patch_") as tmp:
        patch_dir = Path(tmp) / "SchoolERP"
        patch_dir.mkdir(parents=True)

        try:
            build_views(patch_dir)
            build_server_js(patch_dir)
            build_templates(patch_dir, mode=mode, fernet_key=args.fernet_key)
            create_zip(patch_dir, zip_path)
        except Exception as exc:
            _fail(str(exc))
            return 1

    print()
    print("=" * 60)
    print("  PATCH BUILD COMPLETE!")
    print("=" * 60)
    print(f"  Output Package : {zip_path}")
    print()
    print("  FILES INCLUDED IN THIS UPDATE:")
    print("    - core/views.pyc              (compiled bytecode)")
    print("    - core/views.py               (loader shim)")
    print("    - whatsapp_service/server.js  (obfuscated JavaScript)")
    print("    - templates/core/whatsapp_dashboard.html")
    if mode == "new-key-all":
        print("    - core/loaders.pyc + all encrypted templates")
    print()
    print("  HOW TO APPLY TO CLIENT PC:")
    print("  -------------------------------------------------------")
    print("  1. Close School ERP on the client's machine.")
    print("  2. Extract the ZIP directly into their SchoolERP folder")
    print("     (click 'Replace all files' when prompted).")
    print("  3. Start School ERP.")
    print("=" * 60)
    return 0


if __name__ == "__main__":
    sys.exit(main())
